-- April Taylor --
-- Q1: FOREIGN KEYS ADDED --
ALTER TABLE ORDERS
ADD CONSTRAINT FK_ORDERS_USERID FOREIGN KEY (USERID) REFERENCES USERBASE(USERID)
ADD CONSTRAINT FK_ORDERS_PRODUCTCODE FOREIGN KEY (PRODUCTCODE) 
REFERENCES PRODUCTLIST(PRODUCTCODE);

ALTER TABLE REVIEWS
ADD CONSTRAINT FK_REVIEWS_USERID FOREIGN KEY (USERID) REFERENCES USERBASE(USERID)
ADD CONSTRAINT FK_REVIEWS_PRODUCTCODE FOREIGN KEY (PRODUCTCODE) 
REFERENCES PRODUCTLIST(PRODUCTCODE);

ALTER TABLE USERLIBRARY
ADD CONSTRAINT FK_USERLIBRARY_USERID FOREIGN KEY (USERID) REFERENCES USERBASE(USERID)
ADD CONSTRAINT FK_USERLIBRARY_PRODUCTCODE FOREIGN KEY (PRODUCTCODE) 
REFERENCES PRODUCTLIST(PRODUCTCODE);

-- Q2: DISPLAY USERNAMES OF USERS 18 AND OLDER --
SELECT FIRSTNAME || ' ' || LASTNAME AS FULLNAME, USERNAME
FROM USERBASE
WHERE BIRTHDAY <= ADD_MONTHS(SYSDATE, -18);

-- Q3 FIND MAX / AVG LENGTH OF A USERNAME --
SELECT MAX(LENGTH(USERNAME)), AVG(LENGTH(USERNAME))
FROM USERBASE;

-- Q4 DISPLAY QUESTION THAT STARTS WITH "WHAT IS" OR "WHAT WAS"
SELECT QUESTION
FROM SECURITYQUESTION
WHERE QUESTION LIKE 'WHAT IS%' OR QUESTION LIKE 'WHAT WAS%';


-- Q5 DISPLAY PRODUCTCODE, LOWEST RATING
SELECT PRODUCTCODE, MIN(RATING), COUNT(REVIEW)
FROM REVIEWS
GROUP BY PRODUCTCODE
ORDER BY COUNT(REVIEW) DESC;

-- Q6 DISPLAY ANY PRODUCTCODE RANKED IN POSITION 1 & # OF USERS IN THAT POSITION
SELECT PRODUCTCODE, COUNT(USERID)
FROM WISHLIST
WHERE POSITION = 1
GROUP BY PRODUCTCODE;

-- Q7 DISPLAY USERID AND TOTAL AMOUNT FOR USERS IN ORDERS
SELECT USERID, SUM(PRICE) AS TOTAL_SPENT
FROM ORDERS
GROUP BY USERID;

-- QUESTION 8 --
SELECT SUM(PRICE) AS GROSSPROFIT
FROM ORDERS
GROUP BY PURCHASEDATE 
ORDER BY SUM(PRICE) DESC;

-- QUESTION 9 --
SELECT PRODUCTCODE, SUM(HOURSPLAYED) AS TOTALHOURSPLAYED
FROM USERLIBRARY
GROUP BY PRODUCTCODE 
ORDER BY SUM(HOURSPLAYED) DESC
FETCH NEXT 5 ROWS ONLY;

-- QUESTION 10 --
SELECT USERID, COUNT(PENALTY) AS TOTALINFRACTIONS
FROM INFRACTIONS
GROUP BY USERID
ORDER BY COUNT(PENALTY);

-- QUESTION 11 --
SELECT USERID, RULENUM, COUNT(RULENUM) AS RULEBROKEN
FROM INFRACTIONS
GROUP BY USERID, RULENUM
ORDER BY USERID;

-- QUESTION 12 --
SELECT RULENUM, PENALTY, COUNT(PENALTY) AS TIMESAPPLIED
FROM INFRACTIONS
GROUP BY RULENUM, PENALTY;

-- QUESTION 13 --
SELECT STATUS, AVG(DATEUPDATED - DATESUBMITTED) AS AVERAGETURNAROUNDTIME, 
MAX(DATEUPDATED - DATESUBMITTED) AS MAXTURNAROUNDTIME,
MIN(DATEUPDATED - DATESUBMITTED) AS MINTURNAROUNDTIME
FROM USERSUPPORT
WHERE STATUS = 'CLOSED'
GROUP BY STATUS;

-- QUESTION 14 --
SELECT EMAIL, ISSUE, COUNT(ISSUE) AS ISSUEOCCURENCE
FROM USERSUPPORT
WHERE STATUS = 'NEW'
GROUP BY EMAIL, ISSUE, DATESUBMITTED
ORDER BY COUNT(ISSUE);

-- QUESTION 15 --
SELECT USERID, FIRSTNAME, LASTNAME, PASSWORD
FROM USERBASE
WHERE PASSWORD LIKE '%' || FIRSTNAME || '%'
   OR PASSWORD LIKE '%' || LASTNAME  || '%';

-- QUESTION 16 --
SELECT PUBLISHER, AVG(PRICE)
FROM PRODUCTLIST
GROUP BY PUBLISHER
ORDER BY PUBLISHER ASC;

-- QUESTION 17 --
CREATE OR REPLACE VIEW PRODUCTSALE AS
SELECT PRODUCTNAME, PRICE - (PRICE * 0.25) AS SALEPRICE
FROM PRODUCTLIST
WHERE RELEASEDATE <=  ADD_MONTHS(SYSDATE, 60);

SELECT * FROM PRODUCTSALE;

-- QUESTION 18 --
SELECT MAX(PRICE) AS MAXPRICE, MIN(PRICE) AS MINPRICE
FROM PRODUCTLIST
GROUP BY GENRE;

-- QUESTION 19 --
CREATE OR REPLACE VIEW CHATLOG_1_VIEW AS
SELECT *
FROM CHATLOG
WHERE DATESENT BETWEEN SYSDATE AND SYSDATE - 7;

-- QUESTION 20 --
CREATE OR REPLACE VIEW INFRACTIONS_VIEW AS
SELECT USERID, DATEASSIGNED, PENALTY
FROM INFRACTIONS
WHERE PENALTY IS NOT NULL AND PENALTY >= ADD_MONTHS(SYSDATE, -1);