
ALTER TABLE ORDERS
   ADD CONSTRAINT FK_ORDERS_USERID 
      FOREIGN KEY (USERID) REFERENCES USERBASE(USERID)

   ADD CONSTRAINT FK_ORDERS_PRODUCTCODE 
      FOREIGN KEY (PRODUCTCODE) REFERENCES PRODUCTLIST(PRODUCTCODE);

ALTER TABLE REVIEWS
   ADD CONSTRAINT FK_REVIEWS_USERID 
      FOREIGN KEY (USERID) REFERENCES USERBASE(USERID)
   ADD CONSTRAINT FK_REVIEWS_PRODUCTCODE 
      FOREIGN KEY (PRODUCTCODE) REFERENCES PRODUCTLIST(PRODUCTCODE);

ALTER TABLE USERLIBRARY
   ADD CONSTRAINT FK_USERLIBRARY_USERID 
      FOREIGN KEY (USERID) REFERENCES USERBASE(USERID)
   ADD CONSTRAINT FK_USERLIBRARY_PRODUCTCODE 
      FOREIGN KEY (PRODUCTCODE) REFERENCES PRODUCTLIST(PRODUCTCODE);


SELECT FIRSTNAME || ' ' || LASTNAME AS FULLNAME, USERNAME
FROM USERBASE
WHERE BIRTHDAY <= ADD_MONTHS(SYSDATE, -216);


SELECT MAX(LENGTH(USERNAME)), AVG(LENGTH(USERNAME))
FROM USERBASE;


SELECT QUESTION
FROM SECURITYQUESTION
WHERE QUESTION LIKE 'WHAT IS%' OR QUESTION LIKE 'WHAT WAS%';



SELECT PRODUCTCODE, MIN(RATING) AS MIN_RATING, COUNT(*) AS TOTAL_REVIEWS
FROM REVIEWS
GROUP BY PRODUCTCODE
ORDER BY TOTAL_REVIEWS DESC;


SELECT PRODUCTCODE, COUNT(USERID)
FROM WISHLIST
WHERE POSITION = 1
GROUP BY PRODUCTCODE;


SELECT O.USERID, SUM(P.PRICE) AS TOTAL_SPENT
FROM ORDERS O
   JOIN PRODUCTLIST P ON P.PRODUCTCODE = O.PRODUCTCODE
GROUP BY O.USERID;


SELECT O.PURCHASEDATE, SUM(P.PRICE) AS GROSSPROFIT
FROM ORDERS O
   JOIN PRODUCTLIST P ON P.PRODUCTCODE = O.PRODUCTCODE
GROUP BY O.PURCHASEDATE 
ORDER BY GROSSPROFIT DESC;


SELECT PRODUCTCODE, SUM(HOURSPLAYED) AS TOTALHOURSPLAYED
FROM USERLIBRARY
GROUP BY PRODUCTCODE 
ORDER BY TOTALHOURSPLAYED DESC FETCH NEXT 5 ROWS ONLY;


SELECT USERID, COUNT(INFRACTIONID) AS TOTALINFRACTIONS
FROM INFRACTIONS
GROUP BY USERID
ORDER BY TOTALINFRACTIONS;


SELECT USERID, RULENUM, COUNT(RULENUM) AS RULEBROKEN
FROM INFRACTIONS
GROUP BY USERID, RULENUM
ORDER BY USERID;


SELECT RULENUM, PENALTY, COUNT(PENALTY) AS TIMESAPPLIED
FROM INFRACTIONS
GROUP BY RULENUM, PENALTY;


SELECT STATUS, AVG(DATEUPDATED - DATESUBMITTED) AS AVERAGETURNAROUNDTIME, 
MAX(DATEUPDATED - DATESUBMITTED) AS MAXTURNAROUNDTIME,
MIN(DATEUPDATED - DATESUBMITTED) AS MINTURNAROUNDTIME
FROM USERSUPPORT
WHERE STATUS = 'CLOSED'
GROUP BY STATUS;


SELECT EMAIL, ISSUE, COUNT(ISSUE) AS ISSUEOCCURENCE
FROM USERSUPPORT
WHERE STATUS = 'NEW'
GROUP BY EMAIL, ISSUE
ORDER BY ISSUEOCCURENCE;


SELECT USERID, FIRSTNAME, LASTNAME, PASSWORD
FROM USERBASE
WHERE PASSWORD LIKE '%' || FIRSTNAME || '%'
   OR PASSWORD LIKE '%' || LASTNAME  || '%';


SELECT PUBLISHER, AVG(PRICE)
FROM PRODUCTLIST
GROUP BY PUBLISHER
ORDER BY PUBLISHER ASC;


CREATE OR REPLACE VIEW PRODUCTSALE AS
SELECT PRODUCTNAME, PRICE - (PRICE * 0.25) AS SALEPRICE
FROM PRODUCTLIST
WHERE RELEASEDATE <=  ADD_MONTHS(SYSDATE, -60);

SELECT * FROM PRODUCTSALE;


SELECT MAX(PRICE) AS MAXPRICE, MIN(PRICE) AS MINPRICE
FROM PRODUCTLIST
GROUP BY GENRE;


CREATE OR REPLACE VIEW CHATLOG_1_VIEW AS
SELECT *
FROM CHATLOG
WHERE DATESENT BETWEEN SYSDATE -7 AND SYSDATE;


CREATE OR REPLACE VIEW INFRACTIONS_VIEW AS
SELECT USERID, DATEASSIGNED, PENALTY
FROM INFRACTIONS

WHERE PENALTY IS NOT NULL 
   AND DATEASSIGNED >= ADD_MONTHS(SYSDATE, -1);
