-- April Taylor --
--QUESTION 1 --
SELECT USERNAME, MIN(RATING) AS LOWEST_RATING
FROM USERBASE 
LEFT JOIN REVIEWS ON USERBASE.USERID = REVIEWS.USERID
GROUP BY USERNAME;

-- QUESTION 2--
SELECT EMAIL, QUESTION, ANSWER 
FROM USERBASE
LEFT JOIN SECURITYQUESTION ON  USERBASE.USERID = SECURITYQUESTION.USERID;

-- QUESTION 3--
SELECT FIRSTNAME, EMAIL, WALLETFUNDS
FROM USERBASE
FULL OUTER JOIN WISHLIST ON USERBASE.USERID = WISHLIST.USERID
WHERE WISHLIST.USERID IS NULL;

-- QUESTION 4 --
SELECT USERNAME, COUNT(ORDERID) AS PRODUCTS_ORDERED
FROM USERBASE
INNER JOIN ORDERS ON USERBASE.USERID = ORDERS.USERID
GROUP BY USERNAME;

-- QUESTION 5 --
SELECT FIRSTNAME, LASTNAME, TO_CHAR(SYSDATE, 'YYYY') - TO_CHAR(BIRTHDAY, 'YYYY') AS AGE
FROM USERBASE
INNER JOIN ORDERS ON USERBASE.USERID = ORDERS.USERID
WHERE PURCHASEDATE >= ADD_MONTHS(SYSDATE, -60);

-- QUESTION 6 --
SELECT USERNAME, BIRTHDAY
FROM USERBASE 
WHERE USERID IN (SELECT USERID FROM FRIENDSLIST GROUP BY USERID 
HAVING COUNT(FRIENDID)>= (SELECT MAX(FRIENDCOUNT) AS FRIEND_COUNT 
FROM (SELECT USERID, COUNT(FRIENDID) AS FRIENDCOUNT
FROM FRIENDSLIST
GROUP BY USERID)));

-- QUESTION 7 --
SELECT PRODUCTNAME, RELEASEDATE, PRICE, DESCRIPTION
FROM PRODUCTLIST
JOIN WISHLIST ON PRODUCTLIST.PRODUCTCODE = WISHLIST.PRODUCTCODE;

-- QUESTION 8 --
SELECT PRODUCTNAME, MAX(RATING) AS MAX_RATING, COUNT(REVIEW) AS TOTAL_REVIEWS
FROM REVIEWS
JOIN PRODUCTLIST ON PRODUCTLIST.PRODUCTCODE = REVIEWS.PRODUCTCODE 
GROUP BY PRODUCTNAME;

-- QUESTION 9 --
CREATE OR REPLACE VIEW RATING_VIEW AS
SELECT PRODUCTNAME, GENRE, RATING
FROM PRODUCTLIST
JOIN REVIEWS ON PRODUCTLIST.PRODUCTCODE = REVIEWS.PRODUCTCODE
WHERE RATING IN (1, 5)
ORDER BY RATING ASC;

-- QUESTION 10 --
SELECT COUNT(ORDERID) AS PRODUCTS_ORDERED
FROM PRODUCTLIST
JOIN ORDERS ON PRODUCTLIST.PRODUCTCODE = ORDERS.PRODUCTCODE
GROUP BY GENRE
ORDER BY GENRE ASC;

-- QUESTION 11 --
CREATE OR REPLACE VIEW INFO_ON_PRODUCTS AS
SELECT PUBLISHER, AVG(PRICE) AS AVERAGE_PRICE, SUM(HOURSPLAYED) AS TOTAL_HOURS_PLAYED
FROM PRODUCTLIST
JOIN USERLIBRARY ON PRODUCTLIST.PRODUCTCODE = USERLIBRARY.PRODUCTCODE
GROUP BY PUBLISHER
ORDER BY PUBLISHER ASC;

-- QUESTION 12 --
SELECT B.PUBLISHER, SUM(A.PRICE) AS TOTAL_SPENT
FROM ORDERS A
JOIN PRODUCTLIST B ON A.PRODUCTCODE = B.PRODUCTCODE
GROUP BY B.PUBLISHER
ORDER BY TOTAL_SPENT DESC;

-- QUESTION 13 --
SELECT TICKETID, USERNAME, USERBASE.EMAIL, ISSUE
FROM USERSUPPORT
INNER JOIN USERBASE ON USERSUPPORT.EMAIL = USERBASE.EMAIL
WHERE STATUS IN ('NEW', 'IN PROGRESS')
ORDER BY DATEUPDATED DESC;

-- QUESTION 14 --
SELECT USERNAME, COUNT(TICKETID) AS TOTAL_SPENT
FROM USERSUPPORT
INNER JOIN USERBASE ON USERSUPPORT.EMAIL = USERBASE.EMAIL
GROUP BY USERNAME;

-- QUESTION 15 --
SELECT USERID, USERSUPPORT.EMAIL
FROM USERSUPPORT
LEFT JOIN USERBASE ON USERSUPPORT.EMAIL = USERBASE.EMAIL
WHERE UPPER(USERSUPPORT.EMAIL) LIKE UPPER('%' || FIRSTNAME || '%') 
OR UPPER(USERSUPPORT.EMAIL) LIKE UPPER('%' || LASTNAME || '%');

-- QUESTION 16 --
SELECT USERSUPPORT.EMAIL
FROM USERSUPPORT
LEFT JOIN USERBASE ON USERSUPPORT.EMAIL = USERBASE.EMAIL
WHERE STATUS IN ('NEW', 'IN PROGRESS') AND USERBASE.EMAIL IS NULL;

-- QUESTION 17 ---
SELECT TICKETID, FIRSTNAME, LASTNAME, USERNAME
FROM USERSUPPORT
RIGHT JOIN USERBASE ON USERSUPPORT.EMAIL = USERBASE.EMAIL
WHERE ISSUE LIKE '% || USERNAME || %';

-- QUESTION 18 --
SELECT USERNAME, PASSWORD, USERSUPPORT.EMAIL
FROM USERBASE
RIGHT JOIN USERSUPPORT ON USERBASE.EMAIL = USERSUPPORT.EMAIL;

-- QUESTION 19 --
-- APRIL TAYLOR --
CREATE OR REPLACE VIEW PENALTY_INFRACTION_VIEW AS
SELECT USERNAME, DATEASSIGNED, PENALTY
FROM INFRACTIONS
JOIN USERBASE ON INFRACTIONS.USERID = USERBASE.USERID
WHERE PENALTY IS NOT NULL AND DATEASSIGNED >= ADD_MONTHS(SYSDATE, -1);

-- QUESTION 20 --
SELECT USERNAME, EMAIL
FROM USERBASE
LEFT JOIN INFRACTIONS ON USERBASE.USERID = INFRACTIONS.USERID
WHERE BIRTHDAY <= ADD_MONTHS(SYSDATE, -216) AND DATEASSIGNED <= ADD_MONTHS(SYSDATE, -4);

-- QUESTION 21 --
SELECT A.USERNAME, B.DATEASSIGNED, C.RULENUM || '.  ' || C.TITLE AS FULL_GUIDELINE
FROM INFRACTIONS B
JOIN USERBASE A ON B.USERID = A.USERID
JOIN COMMUNITYRULES C ON B.RULENUM = C.RULENUM
ORDER BY A.USERNAME, B.DATEASSIGNED;

-- QUESTION 22 --
SELECT A.USERID, A.USERNAME, A.EMAIL, SUM(C.SEVERITYPOINT) AS TOTAL_SEVERITY_POINTS
FROM USERBASE A
JOIN INFRACTIONS B ON A.USERID = B.USERID
JOIN COMMUNITYRULES C ON B.RULENUM = C.RULENUM
GROUP BY A.USERID, A.USERNAME, A.EMAIL
ORDER BY A.USERID, A.USERNAME, A.EMAIL;

-- QUESTION 23 --
SELECT C.TITLE, C.DESCRIPTION, A.PENALTY
FROM INFRACTIONS A
JOIN COMMUNITYRULES C ON A.RULENUM = C.RULENUM
ORDER BY C.TITLE;

-- QUESTION 24 --
SELECT A.USERNAME, COUNT(B.INFRACTIONID) AS TOTAL_INFRACTIONS
FROM INFRACTIONS B
JOIN USERBASE A ON B.USERID = A.USERID
GROUP BY A.USERNAME
HAVING COUNT(B.INFRACTIONID) >= 15;