
SELECT A.USERID
FROM USERBASE A
LEFT JOIN ORDERS B ON A.USERID = B.USERID
WHERE B.ORDERID IS NULL
ORDER BY A.USERID;


SELECT A.PRODUCTCODE
FROM PRODUCTLIST A
LEFT JOIN REVIEWS B ON A.PRODUCTCODE = B.PRODUCTCODE
WHERE B.PRODUCTCODE IS NULL
ORDER BY A.PRODUCTCODE;


SELECT USERID, FIRSTNAME, LASTNAME, USERNAME, EMAIL, BIRTHDAY, 'ADULT' AS AGE_STATUS
FROM USERBASE
WHERE BIRTHDAY <= ADD_MONTHS(SYSDATE, -216)
UNION 
SELECT USERID, FIRSTNAME, LASTNAME, USERNAME, EMAIL, BIRTHDAY, 'MINOR' AS AGE_STATUS
FROM USERBASE
WHERE BIRTHDAY > ADD_MONTHS(SYSDATE, -216);


SELECT A.*, 'ON SALE' AS "SALE PRICE"
FROM PRODUCTLIST A
WHERE PRICE > 20.00 OR PRICE IS NULL
UNION
SELECT A.*, 'BASE PRICE'
FROM PRODUCTLIST A
WHERE NOT PRICE <= 20.00;


SELECT USERID
FROM USERLIBRARY
WHERE PRODUCTCODE = 'GAME6'
INTERSECT
SELECT USERID
FROM USERPROFILE;


SELECT PRODUCTCODE
FROM WISHLIST
WHERE POSITION <=2
INTERSECT 
SELECT PRODUCTCODE 
FROM REVIEWS
WHERE RATING >= 3;


SELECT A.USERNAME, B.USERNAME, A.BIRTHDAY
FROM USERBASE A, USERBASE B
WHERE A.USERID < B.USERID AND  A.BIRTHDAY = B.BIRTHDAY;


SELECT COUNT(*) AS "CARTESIAN PRODUCT"
FROM USERLIBRARY
CROSS JOIN WISHLIST;


SELECT USERNAME
FROM USERBASE 
UNION ALL
SELECT PUBLISHER
FROM PRODUCTLIST;


SELECT CHATID, CONTENT
FROM CHATLOG
UNION ALL
SELECT USERID, DESCRIPTION
FROM USERPROFILE;


SELECT USERNAME
FROM USERBASE
UNION
SELECT PENALTY
FROM INFRACTIONS;


SELECT A.TITLE, A.DESCRIPTION
FROM COMMUNITYRULES A
LEFT JOIN INFRACTIONS B ON A.RULENUM = B.RULENUM
WHERE B.RULENUM IS NULL;


SELECT USERNAME, EMAIL
FROM USERBASE A
JOIN INFRACTIONS B ON A.USERID = B.USERID
WHERE PENALTY IS NULL;


SELECT DATEASSIGNED FROM INFRACTIONS
INTERSECT
SELECT DATESUBMITTED FROM USERSUPPORT;


SELECT A.TITLE, B.PENALTY
FROM COMMUNITYRULES A
JOIN INFRACTIONS B ON A.RULENUM = B.RULENUM
ORDER BY TITLE;


SELECT RULENUM, TITLE, DESCRIPTION, SEVERITYPOINT, 'BANNABLE' AS STATUS 
FROM COMMUNITYRULES 
WHERE SEVERITYPOINT >= 10
UNION
SELECT RULENUM, TITLE, DESCRIPTION, SEVERITYPOINT, 'APPEALABLE' AS STATUS 
FROM COMMUNITYRULES 
WHERE SEVERITYPOINT < 10;


SELECT TICKETID, EMAIL, ISSUE, DATESUBMITTED, DATEUPDATED, STATUS, 'HIGH PRIORITY' AS TICKET_NOT_CLOSED_UPDATED
FROM USERSUPPORT
WHERE STATUS <> 'CLOSED' 
INTERSECT
SELECT TICKETID, EMAIL, ISSUE, DATESUBMITTED, DATEUPDATED, STATUS, 'HIGH PRIORITY' AS TICKET_NOT_CLOSED_UPDATED
FROM USERSUPPORT
WHERE DATEUPDATED < SYSDATE - 7;


SELECT * FROM USERSUPPORT
CROSS JOIN INFRACTIONS;


SELECT TICKETID, DATEUPDATED
FROM USERSUPPORT
WHERE STATUS = 'CLOSED'
INTERSECT 
SELECT TICKETID, DATEUPDATED
FROM USERSUPPORT
WHERE TRUNC(DATEUPDATED) = TRUNC(CURRENT_DATE);

SELECT USERID, FIRSTNAME AS NAME, BIRTHDAY AS ACTIVITYDATE
FROM USERBASE
UNION ALL
SELECT USERID, PENALTY AS NAME, DATEASSIGNED AS ACTIVITYDATE
FROM INFRACTIONS;

