-- APRIL TAYLOR --
-- QUESTION 1 --
SELECT A.USERID
FROM USERBASE A
LEFT JOIN ORDERS B ON A.USERID = B.USERID
WHERE ORDERID IS NULL
ORDER BY USERID;
-- QUESTION 2 --
SELECT A.PRODUCTCODE
FROM PRODUCTLIST A
LEFT JOIN REVIEWS B ON A.PRODUCTCODE = B.PRODUCTCODE
WHERE REVIEW IS NULL
ORDER BY PRODUCTCODE;

-- QUESTION 3 --
SELECT USERID, FIRSTNAME, LASTNAME, USERNAME, EMAIL, BIRTHDAY, 'ADULT' AS AGE_STATUS
FROM USERBASE
WHERE BIRTHDAY <= ADD_MONTHS(SYSDATE, -216)
UNION 
SELECT USERID, FIRSTNAME, LASTNAME, USERNAME, EMAIL, BIRTHDAY, 'MINOR' AS AGE_STATUS
FROM USERBASE
WHERE BIRTHDAY > ADD_MONTHS(SYSDATE, -216);

-- QUESTION 4 --
SELECT A.*, 'ON SALE' AS "SALE PRICE"
FROM PRODUCTLIST A
WHERE PRICE <= 20.00
UNION
SELECT A.*, 'BASE PRICE'
FROM PRODUCTLIST A
WHERE NOT PRICE <= 20.00;

-- QUESTION 5 --
SELECT USERID
FROM USERLIBRARY
WHERE PRODUCTCODE = 'GAME6'
INTERSECT
SELECT USERID
FROM USERPROFILE;

-- QUESTION 6 --
SELECT PRODUCTCODE
FROM WISHLIST
WHERE POSITION <=2
INTERSECT 
SELECT PRODUCTCODE 
FROM REVIEWS
WHERE RATING >= 3;

-- QUESTION 7 --
SELECT A.USERNAME, B.USERNAME, A.BIRTHDAY
FROM USERBASE A, USERBASE B
WHERE A.USERID <> B.USERID AND  A.BIRTHDAY = B.BIRTHDAY;

-- QUESTION 8 --
SELECT COUNT(*) AS "CARTESIAN PRODUCT"
FROM USERLIBRARY
CROSS JOIN WISHLIST;

-- QUESTION 9 --
SELECT USERNAME
FROM USERBASE 
UNION ALL
SELECT PUBLISHER
FROM PRODUCTLIST;

-- QUESTION 10 --
SELECT CHATID, CONTENT
FROM CHATLOG
UNION ALL
SELECT USERID, DESCRIPTION
FROM USERPROFILE;

-- QUESTION 11 --
SELECT USERNAME
FROM USERBASE
UNION
SELECT PENALTY
FROM INFRACTIONS
WHERE INFRACTIONID = 0;

-- QUESTION 12 --
SELECT A.TITLE, A.DESCRIPTION
FROM COMMUNITYRULES A
LEFT JOIN INFRACTIONS B ON A.RULENUM = B.RULENUM
WHERE B.RULENUM = 0;

-- QUESTION 13 -- 
SELECT USERNAME, EMAIL
FROM USERBASE A
JOIN INFRACTIONS B ON A.USERID = B.USERID
WHERE NOT PENALTY IS NULL;

-- QUESTION 14 --
SELECT DATEASSIGNED FROM INFRACTIONS
INTERSECT
SELECT DATESUBMITTED FROM USERSUPPORT;

-- QUESTION 15 --
SELECT A.TITLE, B.PENALTY
FROM COMMUNITYRULES A
JOIN INFRACTIONS B ON A.RULENUM = B.RULENUM
ORDER BY TITLE;

-- QUESTION 16 --
SELECT RULENUM, TITLE, DESCRIPTION, SEVERITYPOINT, 'BANNABLE' AS STATUS 
FROM COMMUNITYRULES 
WHERE SEVERITYPOINT >= 10
UNION
SELECT RULENUM, TITLE, DESCRIPTION, SEVERITYPOINT, 'APPEALABLE' AS STATUS 
FROM COMMUNITYRULES 
WHERE SEVERITYPOINT < 10;

-- QUESTION 17 --
SELECT TICKETID, EMAIL, ISSUE, DATESUBMITTED, DATEUPDATED, STATUS, 'HIGH PRIORITY' AS TICKET_NOT_CLOSED_UPDATED
FROM USERSUPPORT
WHERE STATUS <> 'CLOSED' 
INTERSECT
SELECT TICKETID, EMAIL, ISSUE, DATESUBMITTED, DATEUPDATED, STATUS, 'HIGH PRIORITY' AS TICKET_NOT_CLOSED_UPDATED
FROM USERSUPPORT
WHERE DATEUPDATED < SYSDATE - 7;

-- QUESTION 18 --
SELECT * FROM USERSUPPORT
CROSS JOIN INFRACTIONS;

-- QUESTION 19 --
SELECT TICKETID, DATEUPDATED
FROM USERSUPPORT
WHERE STATUS = 'CLOSED'
INTERSECT 
SELECT TICKETID, DATEUPDATED
FROM USERSUPPORT
WHERE DATEUPDATED = CURRENT_DATE;

-- QUESTION 20 --
SELECT USERID, FIRSTNAME AS NAME, BIRTHDAY AS ACTIVITYDATE
FROM USERBASE
UNION ALL
SELECT USERID, PENALTY AS NAME, DATEASSIGNED AS ACTIVITYDATE
FROM INFRACTIONS;
