
SELECT USERNAME, MIN(RATING) AS LOWEST_RATING
FROM USERBASE 
LEFT JOIN REVIEWS ON USERBASE.USERID = REVIEWS.USERID
GROUP BY USERNAME;


SELECT EMAIL, QUESTION, ANSWER 
FROM USERBASE
LEFT JOIN SECURITYQUESTION ON  USERBASE.USERID = SECURITYQUESTION.USERID;


SELECT FIRSTNAME, EMAIL, WALLETFUNDS
FROM USERBASE
LEFT JOIN WISHLIST ON USERBASE.USERID = WISHLIST.USERID
WHERE WISHLIST.USERID IS NULL;


SELECT USERNAME, COUNT(ORDERID) AS PRODUCTS_ORDERED
FROM USERBASE
INNER JOIN ORDERS ON USERBASE.USERID = ORDERS.USERID
GROUP BY USERNAME;


SELECT FIRSTNAME, LASTNAME, TRUNC(MONTHS_BETWEEN(SYSDATE, BIRTHDAY)/12) AS AGE
FROM USERBASE
INNER JOIN ORDERS ON USERBASE.USERID = ORDERS.USERID
WHERE PURCHASEDATE >= ADD_MONTHS(SYSDATE, -60);


SELECT u.USERNAME, u.BIRTHDAY
FROM USERBASE u
JOIN (
  SELECT USERID
  FROM FRIENDSLIST
  GROUP BY USERID
  HAVING COUNT(*) = (
    SELECT MAX(CNT)
    FROM (SELECT COUNT(*) CNT FROM FRIENDSLIST GROUP BY USERID)
  )
) f ON u.USERID = f.USERID;


SELECT PRODUCTNAME, RELEASEDATE, PRICE, DESCRIPTION
FROM PRODUCTLIST
JOIN WISHLIST ON PRODUCTLIST.PRODUCTCODE = WISHLIST.PRODUCTCODE;


SELECT PRODUCTNAME, MAX(RATING) AS MAX_RATING, COUNT(REVIEW) AS TOTAL_REVIEWS
FROM REVIEWS
JOIN PRODUCTLIST ON PRODUCTLIST.PRODUCTCODE = REVIEWS.PRODUCTCODE 
GROUP BY PRODUCTNAME;


CREATE OR REPLACE VIEW RATING_VIEW AS
SELECT PRODUCTNAME, GENRE, RATING
FROM PRODUCTLIST
JOIN REVIEWS ON PRODUCTLIST.PRODUCTCODE = REVIEWS.PRODUCTCODE
WHERE RATING IN (1, 5)
ORDER BY RATING ASC;


SELECT GENRE, COUNT(ORDERID) AS PRODUCTS_ORDERED
FROM PRODUCTLIST
JOIN ORDERS ON PRODUCTLIST.PRODUCTCODE = ORDERS.PRODUCTCODE
GROUP BY GENRE
ORDER BY GENRE ASC;


CREATE OR REPLACE VIEW INFO_ON_PRODUCTS AS
SELECT PUBLISHER, AVG(PRICE) AS AVERAGE_PRICE, SUM(HOURSPLAYED) AS TOTAL_HOURS_PLAYED
FROM PRODUCTLIST
JOIN USERLIBRARY ON PRODUCTLIST.PRODUCTCODE = USERLIBRARY.PRODUCTCODE
GROUP BY PUBLISHER
ORDER BY PUBLISHER ASC;


SELECT B.PUBLISHER, SUM(A.PRICE) AS TOTAL_SPENT
FROM ORDERS A
JOIN PRODUCTLIST B ON A.PRODUCTCODE = B.PRODUCTCODE
GROUP BY B.PUBLISHER
ORDER BY TOTAL_SPENT DESC;


SELECT TICKETID, USERNAME, USERBASE.EMAIL, ISSUE
FROM USERSUPPORT
INNER JOIN USERBASE ON USERSUPPORT.EMAIL = USERBASE.EMAIL
WHERE STATUS IN ('NEW', 'IN PROGRESS')
ORDER BY DATEUPDATED DESC;


SELECT USERNAME, COUNT(TICKETID) AS TOTAL_TICKETS
FROM USERSUPPORT
INNER JOIN USERBASE ON USERSUPPORT.EMAIL = USERBASE.EMAIL
GROUP BY USERNAME;


SELECT USERID, USERSUPPORT.EMAIL
FROM USERSUPPORT
LEFT JOIN USERBASE ON USERSUPPORT.EMAIL = USERBASE.EMAIL
WHERE UPPER(USERSUPPORT.EMAIL) LIKE UPPER('%' || FIRSTNAME || '%') 
OR UPPER(USERSUPPORT.EMAIL) LIKE UPPER('%' || LASTNAME || '%');


SELECT USERSUPPORT.EMAIL
FROM USERSUPPORT
LEFT JOIN USERBASE ON USERSUPPORT.EMAIL = USERBASE.EMAIL
WHERE STATUS IN ('NEW', 'IN PROGRESS') AND USERBASE.EMAIL IS NULL;


SELECT TICKETID, FIRSTNAME, LASTNAME, USERNAME
FROM USERSUPPORT
RIGHT JOIN USERBASE ON USERSUPPORT.EMAIL = USERBASE.EMAIL
WHERE ISSUE LIKE '%' || USERNAME || '%';


SELECT USERNAME, PASSWORD, USERSUPPORT.EMAIL
FROM USERBASE
RIGHT JOIN USERSUPPORT ON USERBASE.EMAIL = USERSUPPORT.EMAIL;


CREATE OR REPLACE VIEW PENALTY_INFRACTION_VIEW AS
SELECT USERNAME, DATEASSIGNED, PENALTY
FROM INFRACTIONS
JOIN USERBASE ON INFRACTIONS.USERID = USERBASE.USERID
WHERE PENALTY IS NOT NULL AND DATEASSIGNED >= ADD_MONTHS(SYSDATE, -1);


SELECT USERNAME, EMAIL
FROM USERBASE
LEFT JOIN INFRACTIONS ON USERBASE.USERID = INFRACTIONS.USERID
WHERE BIRTHDAY <= ADD_MONTHS(SYSDATE, -216) AND DATEASSIGNED <= ADD_MONTHS(SYSDATE, -4);


SELECT A.USERNAME, B.DATEASSIGNED, C.RULENUM || '.  ' || C.TITLE AS FULL_GUIDELINE
FROM INFRACTIONS B
JOIN USERBASE A ON B.USERID = A.USERID
JOIN COMMUNITYRULES C ON B.RULENUM = C.RULENUM
ORDER BY A.USERNAME, B.DATEASSIGNED;


SELECT A.USERID, A.USERNAME, A.EMAIL, SUM(C.SEVERITYPOINT) AS TOTAL_SEVERITY_POINTS
FROM USERBASE A
JOIN INFRACTIONS B ON A.USERID = B.USERID
JOIN COMMUNITYRULES C ON B.RULENUM = C.RULENUM
GROUP BY A.USERID, A.USERNAME, A.EMAIL
ORDER BY A.USERID, A.USERNAME, A.EMAIL;


SELECT C.TITLE, C.DESCRIPTION, A.PENALTY
FROM INFRACTIONS A
JOIN COMMUNITYRULES C ON A.RULENUM = C.RULENUM
ORDER BY C.TITLE;


SELECT A.USERNAME, COUNT(B.INFRACTIONID) AS TOTAL_INFRACTIONS
FROM INFRACTIONS B
JOIN USERBASE A ON B.USERID = A.USERID
GROUP BY A.USERNAME

HAVING COUNT(B.INFRACTIONID) >= 15;
