-- April Taylor --

-- QUESTION 1 --
    --PART 1 --
ALTER TABLE productlist
ADD (PRICE NUMBER(6,2),
DESCRIPTION VARCHAR(250));

    -- PART 3 --
DROP TABLE STOREFRONT

-- QUESTION 2 --
CREATE TABLE CHATLOG
(CHATID NUMBER(3), RECEIVERID NUMBER(3), SENDERID NUMBER(3), 
DATESENT DATE, CONTENT VAHRCHAR(250),
CONSTRAINT PK_CHATLOG PRIMARY KEY (CHATID),
CONSTRAINT FK_CHATLOG_RECEIVERID FOREIGN KEY (RECEIVERID) REFERENCES USERBASE(USERID,
CONSTRAINT FK_CHATLOG_SENDERID FOREIGN KEY (SENDERID) REFERENCES USERBASE(USERID))

INSERT INTO CHATLOG (CHATID, RECEIVERID, SENDERID, DATESENT, CONTENT)
VALUES (122, 108, 104, '11/9/2024', 'JOIN MY PARTY!!');

INSERT INTO CHATLOG (CHATID, RECEIVERID, SENDERID, DATESENT, CONTENT)
VALUES (342, 105, 101, '09/08/2025', 'WATCH MY STREAM!');

INSERT INTO CHATLOG (CHATID, RECEIVERID, SENDERID, DATESENT, CONTENT)
VALUES (175, 102, 107, '11/12/2025', 'THE PARTY ROOM!');

INSERT INTO CHATLOG (CHATID, RECEIVERID, SENDERID, DATESENT, CONTENT)
VALUES (299, 106, 102, '06/07/2025', 'LIVE CHAT IN GAME!');

INSERT INTO CHATLOG (CHATID, RECEIVERID, SENDERID, DATESENT, CONTENT)
VALUES (582, 103, 105, '07/12/2025', 'JOIN SESSION!');

INSERT INTO CHATLOG (CHATID, RECEIVERID, SENDERID, DATESENT, CONTENT)
VALUES (750, 101, 108, '04/03/2025', 'VIDEO STREAM IS LIVE!');

INSERT INTO CHATLOG (CHATID, RECEIVERID, SENDERID, DATESENT, CONTENT)
VALUES (756, 104, 108, '10/18/2024', 'FREE SUBS, ENTER CHAT!');

INSERT INTO CHATLOG (CHATID, RECEIVERID, SENDERID, DATESENT, CONTENT)
VALUES (628, 107, 104, '02/25/2024', 'JOIN LIVE GAME SESSION!');

-- QUESTION 3 --
CREATE TABLE FRIENDSLIST
(USERID NUMBER(3), FRIENDID NUMBER(3),
CONSTRAINT PK_FRIENDSLIST PRIMARY KEY (USERID, FRIENDID),
CONSTRAINT FK_FRIENDSLIST_USERID FOREIGN KEY (USERID) REFERENCES USERBASE(USERID),
CONSTRAINT FK_FRIENDSLIST_FRIENDID FOREIGN KEY (FRIENDID) REFERENCES USERBASE(USERID));

INSERT INTO FRIENDSLIST (USERID, FRIENDID)
VALUES (101, 111);

INSERT INTO FRIENDSLIST (USERID, FRIENDID)
VALUES (102, 102);

INSERT INTO FRIENDSLIST (USERID, FRIENDID)
VALUES (103, 103);

INSERT INTO FRIENDSLIST (USERID, FRIENDID)
VALUES (104, 104);

INSERT INTO FRIENDSLIST (USERID, FRIENDID)
VALUES (105, 105);

INSERT INTO FRIENDSLIST (USERID, FRIENDID)
VALUES (106, 106);

INSERT INTO FRIENDSLIST (USERID, FRIENDID)
VALUES (107, 107);

INSERT INTO FRIENDSLIST (USERID, FRIENDID)
VALUES (108, 108);

-- QUESTION 4 --
CREATE TABLE WISHLIST
(USERID NUMBER(3), PRODUCTCODE VARCHAR2(5), POSITION NUMBER(3),
CONSTRAINT PK_WISHLIST PRIMARY KEY (USERID, PRODUCTCODE),
CONSTRAINT FK_WISHLIST_USERID FOREIGN KEY (USERID) REFERENCES USERBASE(USERID),
CONSTRAINT FK_WISHLIST_PRODUCTCODE FOREIGN KEY (PRODUCTCODE) REFERENCES PRODUCTLIST(PRODUCTCODE));

INSERT INTO WISHLIST (USERID, PRODUCTCODE, POSITION)
VALUES (101, 'GAME1', 777);

INSERT INTO WISHLIST (USERID, PRODUCTCODE, POSITION)
VALUES (102, 'GAME2', 666);

INSERT INTO WISHLIST (USERID, PRODUCTCODE, POSITION)
VALUES (103, 'GAME3', 555);

INSERT INTO WISHLIST (USERID, PRODUCTCODE, POSITION)
VALUES (104, 'GAME4', 444);

INSERT INTO WISHLIST (USERID, PRODUCTCODE, POSITION)
VALUES (105, 'GAME5', 333);

INSERT INTO WISHLIST (USERID, PRODUCTCODE, POSITION)
VALUES (106, 'GAME6', 222);

INSERT INTO WISHLIST (USERID, PRODUCTCODE, POSITION)
VALUES (107, 'GAME7', 111);

INSERT INTO WISHLIST (USERID, PRODUCTCODE, POSITION)
VALUES (108, 'GAME8', 888);

-- QUESTION 5 --
CREATE TABLE USERPROFILE
(USERID NUMBER(3), IMAGEFILE VARCHAR2(250), DESCRIPTION VARCHAR2(250),
CONSTRAINT PK_USERPROFILE PRIMARY KEY (USERID),
CONSTRAINT FK_USERPROFILE_USERID FOREIGN KEY (USERID) REFERENCES USERBSE(USERID));

INSERT INTO USERPROFILE (USERID, IMAGEFILE, DESCRIPTION)
VALUES (101, 'GAMEPIC', 'I LOVE TO GAME!');

INSERT INTO USERPROFILE (USERID, IMAGEFILE, DESCRIPTION)
VALUES (102, 'FUNPIC', 'GAME DAY!');

INSERT INTO USERPROFILE (USERID, IMAGEFILE, DESCRIPTION)
VALUES (103, 'WORKPIC', 'MY MOTTO: WORK HARD, PLAY HARD!');

INSERT INTO USERPROFILE (USERID, IMAGEFILE, DESCRIPTION)
VALUES (104, 'KITTIEPIC', 'IM ALL ABOUT MY ANIMALS!');

INSERT INTO USERPROFILE (USERID, IMAGEFILE, DESCRIPTION)
VALUES (105, 'NIGHTOUTPIC', 'I AM EXTREMELY SOCIAL');

INSERT INTO USERPROFILE (USERID, IMAGEFILE, DESCRIPTION)
VALUES (106, 'HIKEPIC', 'I LOVE THE OUTDOORS!');

INSERT INTO USERPROFILE (USERID, IMAGEFILE, DESCRIPTION)
VALUES (107, 'PEACEPIC', 'PEACE, LOVE & GAMES!');

INSERT INTO USERPROFILE (USERID, IMAGEFILE, DESCRIPTION)
VALUES (108, 'FUNNYFACEPIC', 'BEING GOOFY AND GAMING!');

-- QUESTION 6 --
CREATE TABLE SECURITYQUESTION
(QUESTIONID NUMBER(3), USERID NUMBER(3), QUESTION VARCHAR2(250), ANSWER VARCHAR2(250),
CONSTRAINT PK_SECURITYQUESTION PRIMARY KEY (QUESTIONID),
CONSTRAINT FK_SECURITYQUESTION_USERID FOREIGN KEY (USERID) REFERENCES USERBASE(USERID));

INSERT INTO SECURITYQUESTION (QUESTIONID, USERID, QUESTION, ANSWER)
VALUES (1, 101, 'WHAT IS YOUR PASSWORD?', 'FISHER223');

INSERT INTO SECURITYQUESTION (QUESTIONID, USERID, QUESTION, ANSWER)
VALUES (2, 102, 'WHO WAS YOUR 4TH GRADE TEACHER?', 'MRS. HILL');

INSERT INTO SECURITYQUESTION (QUESTIONID, USERID, QUESTION, ANSWER)
VALUES (3, 103, 'WHO WAS YOUR CHILDHOOD BESTFRIEND?', 'DONNA');

INSERT INTO SECURITYQUESTION (QUESTIONID, USERID, QUESTION, ANSWER)
VALUES (4, 104, 'WHAT IS YOUR FAVORITE BOOK?', 'ASHES ASHES');

INSERT INTO SECURITYQUESTION (QUESTIONID, USERID, QUESTION, ANSWER)
VALUES (5, 105, 'WHAT STREET DID YOU GROW UP ON?', 'PRIMROSE DRIVE');

INSERT INTO SECURITYQUESTION (QUESTIONID, USERID, QUESTION, ANSWER)
VALUES (6, 106, 'WHAT IS THE MAKE OF YOUR FIRST CAR?', 'JEEP');

INSERT INTO SECURITYQUESTION (QUESTIONID, USERID, QUESTION, ANSWER)
VALUES (7, 107, 'WHAT IS YOUR FAVORITE COLOR?', 'GREEN');

INSERT INTO SECURITYQUESTION (QUESTIONID, USERID, QUESTION, ANSWER)
VALUES (8, 108, 'WHAT IS YOUR MAIDEN NAME?', 'MORGAN');

-- QUESTION 7 --
CREATE TABLE COMMUNITYRULES
(RULENUM NUMBER(3), TITLE VARCHAR2(250), DESCRIPTION VARCHAR2(250), SEVERITYPOINT NUMBER(4),
CONSTRAINT PK_COMMUNITYRULES PRIMARY KEY (RULENUM));

INSERT INTO COMMUNITYRULES (RULENUM, TITLE, DESCRIPTION, SEVERITYPOINT)
VALUES(1, 'CHEATING & FAIR PLAY', 'PLAY FAIR, NO HACKS & NO EXPLOITS', 9);

INSERT INTO COMMUNITYRULES (RULENUM, TITLE, DESCRIPTION, SEVERITYPOINT)
VALUES(2, 'RESPECT & SHARING ETTIQUETTE', 'RESPECT PRIVACY, NO UNAUTHORIZED RECORDINGS', 6);

INSERT INTO COMMUNITYRULES (RULENUM, TITLE, DESCRIPTION, SEVERITYPOINT)
VALUES(3, 'COMMUNICATION', 'USE APPROPRIATE LANGUAGE, NO EXCEPTIONS', 6);

INSERT INTO COMMUNITYRULES (RULENUM, TITLE, DESCRIPTION, SEVERITYPOINT)
VALUES(4, 'TEAMWORK', 'USE POSITIVE COLLABORATIONS: NO RAGE QUITTING', 5);

INSERT INTO COMMUNITYRULES (RULENUM, TITLE, DESCRIPTION, SEVERITYPOINT)
VALUES(5, 'TRADING', 'FAIR DEALS ONLY; NO SCAMMING OR EXPLOITING', 7);

INSERT INTO COMMUNITYRULES (RULENUM, TITLE, DESCRIPTION, SEVERITYPOINT)
VALUES(6, 'SPORTSMANSHIP', 'KEEP THE GAME FUN: NO TOXICITY & NO HARASSMENT', 9);

INSERT INTO COMMUNITYRULES (RULENUM, TITLE, DESCRIPTION, SEVERITYPOINT)
VALUES(7, 'EVENT CONDUCT', 'COMPETE WITH HONOR: FOLLOW ALL RULE AND RESPECT ORGANIZERS', 9);

INSERT INTO COMMUNITYRULES (RULENUM, TITLE, DESCRIPTION, SEVERITYPOINT)
VALUES(8, 'REPORTING', 'KEEP THE COMMUNITY SAFE: REPORT ALL VIOLATIONS', 9);

-- QUESTION 8 --
CREATE TABLE INFRACTIONS
(INFRACTIONID NUMBER(3), USERID NUMBER(3), RULENUM NUMBER(3), DATEASSIGNED DATE, PENALTY VARCHAR2(250),
CONSTRAINT PK_INFRACTIONS PRIMARY KEY (INFRACTIONID),
CONSTRAINT FK_INFRACTIONS_USERID FOREIGN KEY (USERID) REFERENCES USERBASE(USERID),
CONSTRAINT FK_INFRACTIONS_RULENUM FOREIGN KEY (RULENUM) REFERENCES COMMUNITYRULES(RULENUM));

INSERT INTO COMMUNITYRULES (INFRACTIONID, USERID, RULENUM, DATEASSIGNED, PENALTY)
VALUES (192.4, 101, 2, '03/19/2025', 'TEMPORARY BAN FROM PLATFORM FOR THREE MONTHS');

INSERT INTO COMMUNITYRULES (INFRACTIONID, USERID, RULENUM, DATEASSIGNED, PENALTY)
VALUES (200.5, 102, 7, '08/25/2025', 'BAN FROM ORGANIZATION INDEFINITELY');

INSERT INTO COMMUNITYRULES (INFRACTIONID, USERID, RULENUM, DATEASSIGNED, PENALTY)
VALUES (334.2, 103, 3, '02/11/2025', 'CHAT SUSPENSION FOR TWO WEEKS');

INSERT INTO COMMUNITYRULES (INFRACTIONID, USERID, RULENUM, DATEASSIGNED, PENALTY)
VALUES (103.9, 104, 6, '10/31/2025', 'IN GAME SUSPENSION FOR NINETY DAYS');

INSERT INTO COMMUNITYRULES (INFRACTIONID, USERID, RULENUM, DATEASSIGNED, PENALTY)
VALUES (472.3, 105, 8, '05/02/2025', 'MEETING FOR REPORTING INCIDENT STILL IN WORKS');

INSERT INTO COMMUNITYRULES (INFRACTIONID, USERID, RULENUM, DATEASSIGNED, PENALTY)
VALUES (300.7, 106, 1, '12/13/2025', 'PERMANENT BAN FROM PLATFORM');

INSERT INTO COMMUNITYRULES (INFRACTIONID, USERID, RULENUM, DATEASSIGNED, PENALTY)
VALUES (623.9, 107, 4, '01/25/2025', 'SUSPENSION FROM JOINING PARTY FOR TEN DAYS');

INSERT INTO COMMUNITYRULES (INFRACTIONID, USERID, RULENUM, DATEASSIGNED, PENALTY)
VALUES (111.1, 108, 5, '07/04/2025', 'NO TRADES ALLOWED WITH THIS PLAYER INDEFINITELY');

-- QUESTION 9 --
CREATE TABLE USERSUPPORT
(TICKETID NUMBER, EMAIL VARCHAR2(250), ISSUE VARCHAR2(250), DATESUBMITTED DATE,
DATEUPDATED DATE, STATUS VARCHAR2(250),
CONSTRAINT PK_USERSUPPORT PRIMARY KEY (TICKETID));

INSERT INTO USERSUPPORT (TICKETID, EMAIL, ISSUE, DATESUBMITTED, DATEUPDATED, STATUS)
VALUES (222, 'LILYBOMBS@YAHOO.COM', 'UNAUTHORIZED CHARGE', '02/14/2025', '02/16/2025', 'IN PROGRESS');

INSERT INTO USERSUPPORT (TICKETID, EMAIL, ISSUE, DATESUBMITTED, DATEUPDATED, STATUS)
VALUES (032, 'JKNOX@YAHOO.COM', 'FORGOT PASSWORD', '03/13/2025', '03/13/2025', 'CLOSED');

INSERT INTO USERSUPPORT (TICKETID, EMAIL, ISSUE, DATESUBMITTED, DATEUPDATED, STATUS)
VALUES (018, 'RPGLADY@GMAIL.COM', 'GAME FREEZE', '10/27/2025', '10/27/2025', 'CLOSED');

INSERT INTO USERSUPPORT (TICKETID, EMAIL, ISSUE, DATESUBMITTED, DATEUPDATED, STATUS)
VALUES (452, 'BOSSBURGERS@GMAIL.COM', 'UNABLE TO JOIN PARTY', '10/09/2025', '10/10/2025', 'IN PROGRESS');

INSERT INTO USERSUPPORT (TICKETID, EMAIL, ISSUE, DATESUBMITTED, DATEUPDATED, STATUS)
VALUES (239, 'KATCITY@AOL.COM', 'GAME NOT LOADING', '04/02/2025', '04/02/2025', 'NEW');

INSERT INTO USERSUPPORT (TICKETID, EMAIL, ISSUE, DATESUBMITTED, DATEUPDATED, STATUS)
VALUES (552, 'SKULLZONE@MSN.COM', 'ACCOUNT RECOVERY', '08/10/2025', '08/10/2025', 'NEW');

INSERT INTO USERSUPPORT (TICKETID, EMAIL, ISSUE, DATESUBMITTED, DATEUPDATED, STATUS)
VALUES (743, 'SHAWNBRIGS@OUTLOOK.COM', 'IN GAME GLITCHING', '07/21/2025', '07/22/2025', 'IN PROGRESS');

INSERT INTO USERSUPPORT (TICKETID, EMAIL, ISSUE, DATESUBMITTED, DATEUPDATED, STATUS)
VALUES (645, 'GAMERGUY@GMAIL.COM', 'IN GAME PURCHASE NOT WORKING', '11/30/2025', '12/2/2025', 'CLOSED');

-- QUESTION 10 --
    -- PART 1 --
CREATE VIEW UNIQUE_SECURITY_QUESTIONS AS
SELECT DISTINCT QUESTION
FROM SECURITYQUESTION;

    -- PART 2 --
CREATE VIEW NEW_INPROGRESS_TICKETS AS
SELECT TICKETID, EMAIL, ISSUE, DATEUPDATED
FROM USERSUPPORT
WHERE STATUS IN ('NEW', 'IN PROGRESS')
ORDER BY DATEUPDATED ASC;