
select USER_ID, USERNAME, CREATED, PASSWORD_CHANGE_DATE
from USER_USERS;


select * from USER_TABLES;

describe ORDERS;
  
describe PRODUCTLIST;
  
describe REVIEWS;
  
describe STOREFRONT;
    
describe USERBASE;
   
describe USERLIBRARY;


select * from ORDERS;

select * from PRODUCTLIST;

select * from REVIEWS;

select * from STOREFRONT;
  
select * from USERBASE;
   
select * from USERLIBRARY;


select TABLE_NAME, CONSTRIANT_NAME, CONSTRAINT_TYPE, STATUS
from USER_CONSTRINTS;


select VIEW_NAME, TEXT
from USER_VIEWS;


SELECT USERNAME
FROM USERBASE
ORDER BY USERNAME DESC;


SELECT FIRSTNAME, LASTNAME, USERNAME, PASSWORD, EMAIL
FROM USERBASE
WHERE EMAIL LIKE '%@yahoo.com';


SELECT USERNAME, BIRTHDAY, WALLETFUNDS
FROM USERBASE
WHERE WALLETFUNDS < '25';


SELECT USERID, PRODUCTCODE, HOURSPLAYED
FROM USERLIBRARY
WHERE HOURSPLAYED > 100;


SELECT PRODUCTCODE, HOURSPLAYED
FROM USERLIBRARY
WHERE HOURSPLAYED < 10;


SELECT PUBLISHER FROM PRODUCTLIST;


SELECT PRODUCTNAME, RELEASEDATE, PUBLISHER, GENRE
FROM PRODUCTLIST
ORDER BY GENRE;


SELECT PRODUCTCODE, PUBLISHER, GENRE
FROM PRODUCTLIST
WHERE GENRE = 'Strategy';


SELECT PRODUCTCODE, DESCRIPTION, PRICE
FROM STOREFRONT 
WHERE PRICE > 25
ORDER BY PRICE DESC;


SELECT INVENTORYID, PRICE
FROM STOREFRONT 
ORDER BY PRICE ASC;


SELECT PRODUCTCODE, REVIEW, RATING
FROM REVIEWS
WHERE RATING = '1';


SELECT PRODUCTCODE, REVIEW, RATING
FROM REVIEWS
WHERE RATING >= '4';


SELECT USERID, ORDERID
FROM ORDERS
ORDER BY ORDERID;


SELECT * FROM ORDERS

ORDER BY PURCHASEDATE;
